# Generated by Django 4.2.3 on 2023-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('BB', 'Banco do Brasil'), ('SA', 'Santander'), ('BR', 'Bradesco'), ('IT', 'Itau')], max_length=2),
        ),
    ]
