# Generated by Django 4.2.4 on 2023-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
